# Generated by Django 5.1.4 on 2025-01-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_friendship_options_alter_friendship_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
