# Generated by Django 5.1.5 on 2025-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='p1',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='history',
            name='p2',
        ),
        migrations.AlterField(
            model_name='history',
            name='pWin',
            field=models.CharField(max_length=20),
        ),
    ]
