# Generated by Django 5.1.5 on 2025-01-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_history_user_alter_user_pp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='game_type',
            field=models.CharField(choices=[('TicTacToe', 'TicTacToe'), ('Pong', 'Pong')], default='Undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='pp_link',
            field=models.URLField(blank=True, default='/static/images/dragon.png'),
        ),
    ]
