# Generated by Django 5.1.4 on 2025-01-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_friendship_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='is_online',
        ),
    ]
