# Generated by Django 5.1.4 on 2025-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_friendship_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
