# Generated by Django 5.1.5 on 2025-01-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_history_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pp_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
