# Generated by Django 5.1.5 on 2025-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_pp_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pp_img',
        ),
        migrations.AlterField(
            model_name='user',
            name='pp_link',
            field=models.ImageField(blank=True, default='/static/images/dragon.png', null=True, upload_to='images/profile_pics'),
        ),
    ]
