# Generated by Django 5.1.5 on 2025-01-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_pp_img_alter_user_pp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pp_link',
            field=models.URLField(blank=True, default='http://localhost:8000/media/images/default.png'),
        ),
    ]
