# Generated by Django 5.1.5 on 2025-01-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_pp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pp_link',
            field=models.TextField(blank=True, default='/static/images/dragon.png', null=True),
        ),
    ]
