services:
  db:
    image: postgres:15
    container_name: ${DB_HOST}
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  web:
    container_name: ${WEBSERV_HOST}
    build:
      context: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8443:443"
    volumes:
      - ./app:/app
    depends_on:
      - web
    entrypoint: ["/bin/sh", "/app/nginx_entry.sh"]
volumes:
  postgres_data:
